### ISSUE TITLE
the _id for images is odd

### ISSUE THREAD

**Issue by mhl** [mysociety/popit#755] opened 2015-02-18 11:43 UTC
If you look at the images for a person in PopIt, e.g. https://yournextmp.popit.mysociety.org/api/v0.1/persons/47 there's a surprising _id element included (in the id in there isn't hex, and it's non-ASCII):

        "_id": {
          "_bsontype": "ObjectID",
          "id": "Tèà±Pâ8p,\u0006\r"
        }

... and presumably there's no need to expose the `_bsontype`

**Comment by chrismytton** [comment] 2015-02-18 11:59
Dupe of https://github.com/mysociety/popit/issues/470 (which I reopened the other day)

**Closed by chrismytton** 2015-02-18 11:59 UTC
